"""SystemVerilog Assertion (SVA) generator."""

from typing import List
from .verilog_parser import VerilogModule, Port
from .property_gen import Property


class SVAGenerator:
    """Generate SystemVerilog Assertions from formal properties."""

    def generate_assertion(self, prop: Property, module: VerilogModule) -> str:
        """Generate a named SVA assertion for a property."""
        lines = [
            f"  // Property: {prop.name}",
            f"  // {prop.description}",
            f"  {prop.name}: {prop.formal_expr}",
        ]
        return "\n".join(lines)

    def generate_assumption(self, port: Port) -> str:
        """Generate an SVA assume statement for an input port constraint."""
        lines = [
            f"  // Assumption: input '{port.name}' is well-defined",
            f"  assume_{port.name}: assume property (##0 !$isunknown({port.name}));",
        ]
        return "\n".join(lines)

    def generate_cover(self, prop: Property) -> str:
        """Generate a cover property for reachability checking."""
        return (
            f"  // Cover: {prop.name} is reachable\n"
            f"  cover_{prop.name}: cover property (##[0:10] 1'b1);  // {prop.description[:60]}"
        )

    def generate_full_spec(self, module: VerilogModule, properties: List[Property]) -> str:
        """Generate a complete SVA specification file."""
        lines = []

        # Header
        lines.append(f"// Formal Specification for module: {module.name}")
        lines.append(f"// Generated by formal-circuits-gpt")
        lines.append(f"// Properties: {len(properties)}")
        lines.append("")

        # Module port list
        port_list = ", ".join(p.name for p in module.ports)
        lines.append(f"module {module.name}_spec({port_list});")
        lines.append("")

        # Port declarations
        for port in module.ports:
            width_str = f"[{port.width-1}:0] " if port.width > 1 else ""
            reg_str = " reg" if port.is_reg else ""
            lines.append(f"  {port.direction}{reg_str} {width_str}{port.name};")
        lines.append("")

        # Assumptions (for inputs)
        input_ports = [p for p in module.ports if p.direction == "input"]
        if input_ports:
            lines.append("  // ---- Input Assumptions ----")
            for port in input_ports:
                lines.append(self.generate_assumption(port))
            lines.append("")

        # Assertions grouped by type
        type_order = ["combinational", "sequential", "safety", "liveness"]
        grouped = {t: [] for t in type_order}
        for prop in properties:
            grouped.get(prop.prop_type, grouped["safety"]).append(prop)

        for prop_type in type_order:
            group = grouped[prop_type]
            if group:
                lines.append(f"  // ---- {prop_type.capitalize()} Properties ----")
                for prop in group:
                    lines.append(self.generate_assertion(prop, module))
                    lines.append("")

        # Cover properties
        lines.append("  // ---- Cover Properties ----")
        for prop in properties[:3]:  # Sample covers
            lines.append(self.generate_cover(prop))
        lines.append("")

        lines.append(f"endmodule // {module.name}_spec")

        return "\n".join(lines)

    def to_file(self, spec: str, path: str) -> None:
        """Write SVA spec to file."""
        with open(path, "w") as f:
            f.write(spec)
